#!/bin/sh

#Credit: Aixxe @ aixxe.net
if grep -q lib.so /proc/$(pidof csgo2_linux64)/maps; then
sudo gdb -n -q -batch \
    -ex "attach $(pidof csgo2_linux64)" \
    -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
    -ex "set \$dlclose = (int(*)(void*)) dlclose" \
    -ex "set \$library = \$dlopen(\"$(pwd)/libAimTux.so\", 6)" \
    -ex "call \$dlclose(\$library)" \
    -ex "call \$dlclose(\$library)" \
    -ex "detach" \
    -ex "quit"
fi
